---
name: ex_doc_version_check
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:
  

jobs:
  test:
    name: Check ex_doc version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        run: |
            CURR=`curl -s https://hex.pm/api/packages/ex_doc | jq -r '.latest_stable_version' \
                  grep "\"name\":" | \
                  sort --reverse | \
                  head -n 1 | \
                  awk '{print substr($2, 2, length($2)-3)}'`
            TITLE="\`ex_doc\` ${CURR} released"
            ISSUE_EXISTS=`curl -s https://api.github.com/repos/starbelly/rebar3_ex_doc/issues?state=all&labels=ex_doc_version_check | grep -c "\"title\": \"${TITLE}\""`

            if [ ${ISSUE_EXISTS} -ne 0 ]
            then
              RESP=`curl -L \
                -X POST \
                https://api.github.com/repos/starbelly/rebar3_ex_doc/issues \
                -d '{"title":"${TITLE}","body":"This is an automated report.","labels":["ex_doc_version_check"]}'`
              echo ${RESP}
            fi
